version: "3.9"
services:
  metrics-api:
    image: seatpilot/metrics-api:latest
    env_file: .env.prod
    environment:
      PORT: "9100"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "9100:9100"
    healthcheck:
      test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:9100/healthz"]
      interval: 10s
      timeout: 2s
      retries: 5

  telemetry-ingest:
    image: seatpilot/telemetry-ingest:latest
    env_file: .env.prod
    environment:
      PORT: "8081"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "8081:8081"
    depends_on:
      metrics-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 10s
      timeout: 2s
      retries: 5

  kpi-refresher:
    image: seatpilot/kpi-refresher:latest
    env_file: .env.prod
    depends_on:
      telemetry-ingest:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  checkin:
    image: seatpilot/checkin:latest
    env_file: .env.prod
    environment:
      PORT: "8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "8080:8080"
    depends_on:
      metrics-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 2s
      retries: 5

  wayfinding:
    image: seatpilot/wayfinding:latest
    env_file: .env.prod
    environment:
      PORT: "8082"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "8082:8082"
    depends_on:
      checkin:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./seatpilot.rules.yml:/etc/prometheus/seatpilot.rules.yml:ro"
      - "./ops/prometheus/rules/seatpilot_slo.rules.yml:/etc/prometheus/seatpilot_slo.rules.yml:ro"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    depends_on:
      metrics-api:
        condition: service_healthy
      telemetry-ingest:
        condition: service_healthy

  alertmanager:
    image: prom/alertmanager:latest
    env_file: .env.prod
    restart: unless-stopped
    entrypoint:
      - /bin/sh
      - /etc/alertmanager/entrypoint.sh
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - "./ops/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro"
      - "./ops/alertmanager/entrypoint.sh:/etc/alertmanager/entrypoint.sh:ro"
    ports:
      - "9093:9093"
    depends_on:
      prometheus:
        condition: service_started
