# Prometheus configuration for SeatPilot telemetry + Supabase metrics
#
# Copy this file next to the Prometheus binary and replace the secret placeholder
# before running:
#   export SUPABASE_SERVICE_ROLE_JWT="your-service-role-jwt"
#   envsubst < prometheus.yml > /tmp/prometheus.generated.yml
#   "$PROM_BIN" --config.file=/tmp/prometheus.generated.yml --storage.tsdb.path=./data
#
# Alternatively, edit the password field directly with the real key and run Prometheus
# with --config.file=prometheus.yml.

global:
  scrape_interval: 60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["seatpilot-alertmanager:9093"]

rule_files:
  - /etc/prometheus/seatpilot.rules.yml
  - /etc/prometheus/seatpilot_slo.rules.yml

scrape_configs:
  # Self-scrape so you can see Prometheus' own metrics.
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "seatpilot-internal-metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["metrics-api:8080"]

  - job_name: "telemetry-ingest"
    metrics_path: "/metrics"
    scrape_interval: 15s
    static_configs:
      - targets: ["telemetry-ingest:3001"]
