name: ✨ Feature request
description: Nueva funcionalidad
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Objetivo y valor
    validations: { required: true }
  - type: textarea
    attributes:
      label: Criterios de aceptación
  - type: textarea
    attributes:
      label: Riesgos
