route:
  group_by: ['alertname', 'tenant', 'channel', 'view']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  receiver: slack_primary
  routes:
    - receiver: stdout
      continue: true

receivers:
  - name: slack_primary
    slack_configs:
      - api_url: '__ALERTMANAGER_SLACK_WEBHOOK_URL__'
        channel: '__ALERTMANAGER_SLACK_CHANNEL__'
        send_resolved: true
        title: "[{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }}"
        text: "{{ range .Alerts }}• Afecta: stage={{ .Labels.stage }}, tenant={{ .Labels.tenant }}, channel={{ .Labels.channel }} ({{ .Annotations.description }})\n{{ end }}"

  - name: stdout
    webhook_configs:
      - url: 'http://alert-echo:8081/'
