name: Brand Icons & Tokens Lint

on:
  pull_request:
  workflow_dispatch: {}

jobs:
  lint-brand:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            brand:
              - 'brand/**'
      - name: No-op (sin cambios en brand/)
        if: ${{ steps.changes.outputs.brand != 'true' }}
        run: echo "No brand changes; green by design."
      - uses: pnpm/action-setup@v3
        if: ${{ steps.changes.outputs.brand == 'true' }}
        with: { version: 9 }
      - uses: actions/setup-node@v4
        if: ${{ steps.changes.outputs.brand == 'true' }}
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
        if: ${{ steps.changes.outputs.brand == 'true' }}
      - name: Lint icons/tokens
        if: ${{ steps.changes.outputs.brand == 'true' }}
        run: pnpm run brand:icons:lint
      - name: Build icon previews (si aplica)
        if: ${{ steps.changes.outputs.brand == 'true' }}
        run: |
          if [ -f scripts/brand/build-previews.sh ]; then bash scripts/brand/build-previews.sh; fi
      - name: Upload previews
        if: ${{ always() && steps.changes.outputs.brand == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: brand-previews
          path: brand/icons/previews/**
